export const musicsData = [
  { id: 1, name: 'Arde outra vez', singer: 'Thalles Roberto', votes: 648, visible: true },
  {
    id: 2,
    name: 'Medley - Tu és soberano/Ao Único/Consagração/Louvor ao Rei/Alfa e Omega',
    singer: 'Paz Church SP',
    votes: 313,
    visible: true
  },
  { id: 3, name: 'Terra Seca', singer: 'Fraternidade São João Paulo II', votes: 93, visible: true },
  { id: 4, name: 'Era a mão de Deus', singer: 'Pedro Henrique', votes: 65, visible: true },
  { id: 5, name: 'Faz o Que Ele Diz', singer: 'Comunidade Colo de Deus', votes: 34, visible: true },
  { id: 6, name: 'Pra Quê ?', singer: 'Voz da Verdade', votes: 26, visible: true },
  { id: 7, name: 'Tu és + aguas purificadoras', singer: 'Fhop music', votes: 26, visible: true },
  { id: 8, name: 'Projeto no deserto', singer: 'Voz da verdade', votes: 20, visible: true },
  { id: 9, name: 'Só tu és santo', singer: 'Morada', votes: 19, visible: true },
  { id: 10, name: 'Caminho no deserto', singer: '', votes: 17, visible: true },
  { id: 11, name: 'Essência da Adoração', singer: 'David Quinlan', votes: 16, visible: true },
  { id: 12, name: 'A Grande Viagem', singer: 'Ivonaldo Albuquerque', votes: 14, visible: true },
  { id: 13, name: 'É Ele', singer: 'Drops', votes: 8, visible: true },
  { id: 14, name: 'In menoriam', singer: 'Gabriel Guedes', votes: 8, visible: true },
  { id: 15, name: 'Lugar secreto', singer: 'Gabriela Rocha', votes: 8, visible: true },
  { id: 16, name: 'Marcas de Valor', singer: 'Logos', votes: 8, visible: true },
  { id: 17, name: 'O quão lindo esse nome é', singer: '', votes: 8, visible: true },
  { id: 18, name: 'Santo para sempre', singer: 'Cece winans', votes: 8, visible: true },
  { id: 19, name: 'Forte mão', singer: 'Projeto Sola', votes: 7, visible: true },
  { id: 20, name: 'Mãe', singer: 'Sergio Saas', votes: 5, visible: true },
  { id: 21, name: 'Pr. Lucas', singer: 'O lugar', votes: 5, visible: true },
  { id: 22, name: 'Soberano Deus', singer: 'Juliano Socio', votes: 5, visible: true },
  { id: 23, name: 'Bendizei ao Senho', singer: 'Vencedores por cristo', votes: 5, visible: true },
  { id: 24, name: 'Alegrem-se na esperança', singer: 'Gerson Borges', votes: 4, visible: true },
  { id: 25, name: 'Convívio dos eleitos', singer: 'Juninho Cassimiro', votes: 4, visible: true },
  { id: 26, name: 'Estrela da manhã', singer: 'Arianne', votes: 4, visible: true },
  { id: 27, name: 'Isaías 53', singer: 'Projeto sola', votes: 4, visible: true },
  { id: 28, name: 'Redenção', singer: 'Projeto sola', votes: 4, visible: true },
  { id: 29, name: 'Alto preço', singer: 'Asaph borba', votes: 3, visible: true },
  { id: 30, name: 'Acredite ou não', singer: 'João Alexandre', votes: 3, visible: true },
  { id: 31, name: 'Bondade de Deus', singer: 'Cece winans', votes: 3, visible: true },
  { id: 32, name: 'Fim de tarde no portão', singer: 'Stenio Marcus', votes: 3, visible: true },
  { id: 33, name: 'Festa do universo', singer: 'Israel Subirá', votes: 3, visible: true },
  { id: 34, name: 'Lancemos sobre Deus', singer: 'Vencedores por cristo', votes: 3, visible: true },
  { id: 35, name: 'Meu coração te pertence', singer: 'Salzband', votes: 3, visible: true },
  { id: 36, name: 'O Nome de Jesus é poderoso', singer: 'Ademar de Campos', votes: 3, visible: true },
  { id: 37, name: 'Ousado amor', singer: '', votes: 3, visible: true },
  { id: 38, name: 'Razão de viver', singer: 'Melissa', votes: 3, visible: true },
  { id: 39, name: 'Rei das nações', singer: 'Paulo César Baruk', votes: 3, visible: true },
  { id: 40, name: 'Solta o cabo da nau', singer: 'Hino da harpa 467', votes: 3, visible: true },
  { id: 41, name: 'Só preciso estar', singer: 'Colo de Deus', votes: 3, visible: true },
  { id: 42, name: 'Tu és tudo', singer: 'Alessandro Vilas Boas', votes: 3, visible: true },
  { id: 43, name: 'Uma vez', singer: 'fhop', votes: 3, visible: true },
  { id: 44, name: 'Ao único', singer: 'Aline Barros', votes: 2, visible: true },
  { id: 45, name: 'Criatura Igual ao Criador', singer: 'André Valadão', votes: 2, visible: true },
  { id: 46, name: 'Getsêmani', singer: 'Leonardo Gonçalves', votes: 2, visible: true },
  { id: 47, name: 'Maranata', singer: 'one sounds e alessandro vilas boas', votes: 2, visible: true },
  { id: 48, name: 'O minha flor', singer: 'Isaac nascimento', votes: 2, visible: true },
  { id: 49, name: 'promessas', singer: 'sarah beatriz', votes: 2, visible: true },
  { id: 50, name: 'Quero conhecer Jesus', singer: 'Alessandro vilas boas', votes: 2, visible: true },
  { id: 51, name: 'Soberano', singer: 'Tony Alisson', votes: 2, visible: true },
  { id: 52, name: 'visceral', singer: 'josé jr', votes: 2, visible: true },
  { id: 53, name: 'Canção de Simeão', singer: 'Drops', votes: 1, visible: true },
  { id: 54, name: 'Casa', singer: 'Comunidade Colo de Deus', votes: 1, visible: true },
  { id: 55, name: 'Eu me rendo', singer: 'Ministério Mergulhar', votes: 1, visible: true },
  { id: 56, name: 'Eu só quero tua presença', singer: 'Theo Rubia', votes: 1, visible: true },
  { id: 57, name: 'Fogo em teus olhos', singer: 'Louvor IIR', votes: 1, visible: true },
  { id: 58, name: 'Hino da vitoria', singer: 'Damares', votes: 1, visible: true },
  { id: 59, name: 'História escrita pelo dedo de Deus', singer: 'Thalles', votes: 1, visible: true },
  { id: 60, name: 'Jesus, meu primeiro amor', singer: 'Fernanda Brum', votes: 1, visible: true },
  { id: 61, name: 'O cordeiro, o leão e o trono', singer: '', votes: 1, visible: true },
  { id: 62, name: 'oceanos', singer: 'Ana Nóbrega', votes: 1, visible: true },
  { id: 63, name: 'Posso descansar', singer: '', votes: 1, visible: true },
  { id: 64, name: 'salmos 126', singer: 'ministério zoe', votes: 1, visible: true },
  { id: 65, name: 'Santo pra sempre', singer: 'Gabriel Guedes', votes: 1, visible: true },
  { id: 66, name: 'Se hoje me toca', singer: 'José Jr', votes: 1, visible: true },
  { id: 67, name: 'Senhor - autoral', singer: 'Paulo felipe', votes: 1, visible: true },
  { id: 68, name: 'Terra seca', singer: 'Fraternidade São João Paulo ll', votes: 1, visible: true },
  { id: 69, name: 'Tudo é teu', singer: 'Drops', votes: 1, visible: true },
  { id: 70, name: 'tu és', singer: 'fhop', votes: 1, visible: true },
  { id: 71, name: 'Yeshua', singer: '', votes: 1, visible: true }
]
